version: "3.7"
services:
  reverse-proxy:
    depends_on:
      - wireme-core-ca
      - aoer-service
      - email-service
      - pushnotification-server
    image: layantha/dev:proxy-hnb
    ports:
      - 8443:81
    networks:
      - wireme-core-ca-network
    restart: always
    container_name: "proxy-ca"

  wireme-core-ca:
    image: pasinduchathura/
    volumes:
      - /home/wireme/logs/core:/logs
      - /home/wireme/reports:/home/reports
      - /home/wireme/migrations:/home/migrations
    environment:
      - FROM_DOCKER=1
      - NODE_ENV=development
      - JWT_EXPIRES_IN=2h
      - DB_TYPE=oracle
      - DB_HOST=124.43.71.173
      - DB_PORT=1521
      - DB_UNAME=boc_test
      - DB_PWORD=password
      - DB_SID=orcl
      - LOG_PORT=24224
      - LOG_HOST=123.231.95.112
      - AOER_PORT=9090
      - AOER_HOST=aoer-service
      - TZ=Asia/Colombo
      - MYSQL_ROOT_HOST='%'
      - SMS_HOST=
      - SMS_PORT=
      - EMAIL_HOST=
      - EMAIL_PORT=
      - EMAIL_UNAME=
      - EMAIL_PWORD=
      - EMAIL_SECURED=false
      - EMAIL_TLS=true
      - EMAIL_SERVICE_HOST=email-service
      - EMAIL_SERVICE_PORT=9091
      - LOG_FILE_PATH=/logs
      - FILE_EXPORT_SERVICE_DIRECTORY=/home/reports
      - MIGRATION_DIRECTORY=/home

    container_name: "wireme-core-ca"
    networks:
      - wireme-core-ca-network
    restart: always

  pushnotification-server:
    image: pasinduchathura/wireme-push-service:v1.0.1
    container_name: pushnotification-server
    restart: always
    volumes:
      - /home/wireme/logs/pushnotification-server:/home/logs/PushService
    environment:
      - DB_HOST=
      - DB_PORT=
      - DB_USER=
      - DB_PASSWORD=
      - DB_NAME=orcl
      - SIGNATURE_SYNQ_SERVICE=wireme-core-ca:8502
      - DEVICEINFO_SYNQ_SERVICE=aoer-service:9090
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@124.43.71.173:1521:orcl
      - CBA_GETDEVICEINFOENDPOINT=http://aoer-service:9090/api/aoer/v1/device-status
      - TZ=Asia/Colombo
    ports:
      - "8502:8500"
      - "8503:8501"
    networks:
      - wireme-core-ca-network

  email-service:
    image: email-service:latest
    container_name: email-service
    ports:
      - 9091:9091
    networks:
      - wireme-core-ca-network
    environment:
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=
      - SPRING_MAIL_PASSWORD=
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
      - SENDER_MAIL_ADDRESS=
      - SENDER_BANK_LOGO=${LOGO}

  aoer-service:
    image: aoer-service:oracle
    container_name: aoer-service
    ports:
      - 9090:9090
    networks:
      - wireme-core-ca-network
    depends_on:
      - email-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@//124.43.71.173:1521/orcl
      - SPRING_DATASOURCE_USERNAME=boc_test
      - SPRING_DATASOURCE_PASSWORD=password
      - EMAIL_BASEURL=http://email-service:9091/api/email/v1

  file-export-service:
    image: pasinduchathura/wireme-file-export-service-boc:v1.0.1
    container_name: file-export-service
    restart: always
    volumes:
      - /home/wireme/reports:/home/reports
      - /home/wireme/logs/file-export:/home/logs/FileExportService
    environment:
      - DB_HOST=124.43.71.173
      - DB_PORT=1521
      - DB_USER=boc_test
      - DB_PASSWORD=password
      - DB_NAME=orcl
      - CLEANUP_DIRECTORY=/home/reports
      - CLEANUP_PERIOD=1
      - CLEANUP_CRON=0 30 01 * * ?
      - FILE_EXPORT_CRON=0 * * * * ?
      - TZ=Asia/Colombo
    ports:
      - "9797:9797"
    networks:
      - wireme-core-ca-network

networks:
  wireme-core-ca-network:
    name: wireme-core-ca-network
